name: Release Artifacts

on:
  push:
    tags:
      - '*'

jobs:
  artifacts-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenCL
        run: |
          sudo add-apt-repository ppa:intel-opencl/intel-opencl
          sudo apt-get update
          sudo apt-get install ocl-icd-opencl-dev
      - uses: actions/checkout@aabbfeb2ce60b5bd82389903509092c4648a9713
      - uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
        with:
          toolchain: stable
      - name: Build release
        run: cargo build --release
      - name: Generate sha256sum
        run: pushd target/release/; sha256sum nano-work-server > nano-work-server.sha256; popd
      - name: Upload artifact
        uses: svenstaro/upload-release-action@14569a2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/nano-work-server
          asset_name: nano-work-server
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload sha256
        uses: svenstaro/upload-release-action@14569a2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/nano-work-server.sha256
          asset_name: nano-work-server.sha256
          tag: ${{ github.ref }}
          overwrite: true
  artifacts-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@aabbfeb2ce60b5bd82389903509092c4648a9713
      - uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
        with:
          toolchain: stable
      - name: Opencl.lib
        run: curl -o OpenCL.lib https://s3.us-east-2.amazonaws.com/repo.nano.org/artifacts/OpenCL.lib
      - name: Build
        run: cargo rustc --release -- -l OpenCL -L "OpenCL.lib"
      - name: Generate sha256sum
        run: pushd target/release/; sha256sum.exe nano-work-server.exe > nano-work-server.exe.sha256; popd
      - name: Upload artifact
        uses: svenstaro/upload-release-action@14569a2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/nano-work-server.exe
          asset_name: nano-work-server.exe
          tag: ${{ github.ref }}
          overwrite: true 
      - name: Upload sha256
        uses: svenstaro/upload-release-action@14569a2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/nano-work-server.exe.sha256
          asset_name: nano-work-server.exe.sha256
          tag: ${{ github.ref }}
          overwrite: true 
