name: RocksDB Release Tests

on: 
  push: 
    tags: '*'

env:
  RELEASE: 1
  artifact: 0
  TEST_USE_ROCKSDB: 1
  
jobs:
  osx_test:
    runs-on: macos-latest
    env:
      BOOST_ROOT: /tmp/boost
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          submodules: "recursive"
      - name: Fetch Deps
        run: TEST=1 ci/actions/osx/install_deps.sh
      - name: Run Tests
        run: ci/build-travis.sh "/tmp/qt/lib/cmake/Qt5";

  gcc_test:
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          submodules: "recursive"
      - name: Fetch Deps
        run: ci/actions/linux/install_deps.sh
      - name: Run Tests
        run: docker run -e TEST_USE_ROCKSDB -v ${PWD}:/workspace nanocurrency/nano-env:gcc /bin/bash -c "cd /workspace && RELEASE=1 ./ci/build-travis.sh /usr/lib/x86_64-linux-gnu/cmake/Qt5 ${PWD}"
  
  clang_test:
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          submodules: "recursive"
      - name: Fetch Deps
        run: ci/actions/linux/install_deps.sh
      - name: Run Tests
        run: docker run -e TEST_USE_ROCKSDB -v ${PWD}:/workspace nanocurrency/nano-env:clang-6 /bin/bash -c "cd /workspace && RELEASE=1 ./ci/build-travis.sh /usr/lib/x86_64-linux-gnu/cmake/Qt5 ${PWD}"
