name: Tests

on: [push, pull_request]

env:
  RELEASE: 0
  artifact: 0
  
jobs:
  osx_test:
    runs-on: macos-latest
    env:
      BOOST_ROOT: /tmp/boost
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          submodules: "recursive"
      - name: Fetch Deps
        run: TEST=1 ci/actions/osx/install_deps.sh
      - name: Run Tests
        run: ci/build-travis.sh "/tmp/qt/lib/cmake/Qt5";

  gcc_test:
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          submodules: "recursive"
      - name: Fetch Deps
        run: ci/actions/linux/install_deps.sh
      - name: Run Tests
        run: docker run -v ${PWD}:/workspace nanocurrency/nano-env:gcc /bin/bash -c "cd /workspace && ./ci/build-travis.sh /usr/lib/x86_64-linux-gnu/cmake/Qt5 ${PWD}"
  
  clang_test:
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          submodules: "recursive"
      - name: Fetch Deps
        run: ci/actions/linux/install_deps.sh
      - name: Run Tests
        run: docker run -v ${PWD}:/workspace nanocurrency/nano-env:clang-6 /bin/bash -c "cd /workspace && ./ci/build-travis.sh /usr/lib/x86_64-linux-gnu/cmake/Qt5 ${PWD}"

  windows_test:
    runs-on: windows-latest
    timeout-minutes: 60
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          submodules: "recursive"
      - name: Windows Defender
        run: ci/actions/windows/disable_windows_defender.ps1

      - name: Fetch Deps
        run: ci/actions/windows/install_deps.ps1
      - name: Run Tests
        run: ci/actions/windows/build.ps1
